config/routes.rb
Rails.application.routes.draw do
   resources :gossips
  root 'static#home'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:show]
  resources :gossips do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    has_many :gossips, through: :users 
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips, dependent: :destroy
    has_many :comments
    has_secure_password
    validates :email, 
        presence: true,
        uniqueness: true,
        format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :first_name, presence: true
    validates :last_name, presence:true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        Comment.create(content: params[:content], user: User.find_by(id: session[:user_id]), gossip: Gossip.find(params[:gossip_id]))
        redirect_to gossip_path(params[:gossip_id])
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index]

  # GET /gossips or /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1 or /gossips/1.json
  def show
    @gossip = Gossip.find(params[:id])
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
    @gossip = Gossip.find(params[:id])
  end

  # POST /gossips or /gossips.json
  def create
    @gossip = Gossip.create(title: params[:title], content: params[:content], user: User.find_by(id: session[:user_id]))  

    if @gossip.save
      redirect_to gossips_path, notice: "Votre nouveau potin a bien été enregistré"
    else
      flash.now[:alert] = "mauvaises entrées de formulaire"
      render :action => 'new'
    end
  end

  # PATCH/PUT /gossips/1 or /gossips/1.json
  def update
    gossip = Gossip.find(params[:id])
    gossip.title = params[:title]
    gossip.content = params[:content]
    if gossip.save
      redirect_to gossips_path, notice: "Le gossip à bien été modifier"
    else
      flash.now[:alert] = "mauvaises entrées de formulaire"
      render :action => 'new'
    end
  end

  # DELETE /gossips/1 or /gossips/1.json
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: "Gossip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gossip_params
      params.require(:gossip).permit(:title, :content)
    end

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create

    user = User.find_by(email: params[:email])


    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gossips_path, notice: "Salut #{user.first_name} !"
            
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :action => 'new'
    end
  end

  

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "A plus !"
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @users = User.all
  end

  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(post_params)
    redirect_to new_session_path
  end

  def create
    
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name],email: params[:email], description: params[:description], age: params[:age].to_i, city: City.find_by(name: params[:city]), password: params[:password], password_confirmation: params[:password_confirmation] )

    if @user.save
      redirect_to new_session_path, notice: "Bienvenue dans The Gossip Project"
    else
      flash.now[:alert] = "mauvaises entrées de formulaire"
      render :action => 'new'
    end
  end

   
   
    
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
    
  private
    
  def post_params
    params.require(:user).permit( :first_name, :last_name, :email, :description , :age, :city, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1> <%=@city.zip_code%> - <%=@city.name%>  </h1>
<p>Voici tous les gossips de <%=@city.name.titleize%> : </p>
 
 <%@city.gossips.each do |gossip|%>
<p><strong><%=gossip.title%></strong></br>
    <em>"<%=gossip.content%>"</em></br>
    De <a href="<%=user_path(gossip.user.id)%>" > <%=gossip.user.first_name%> </a> 
</p>
<%end%>

<%= link_to 'Retour à goosip\'s lande', gossips_path %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<form action= "/gossips/<%=@gossip.id%>" method="PATCH">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   
   
        
    <div class="col">
        <label for="exampleInputEmail1">Titre</label>
        <input type="text" class="form-control" placeholder="<%=@gossip.title%>" name="title">
    </div> 

    

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Contenu</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="<%=@gossip.content%>" name="content"></textarea>
    </div>      

    
    <input type="submit" value="Modifier">
</form>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<h1>The Gossip Project</h1>

<h3> Envie d'écrire une petit potin  <%= User.find_by(id: session[:user_id]).first_name %>?</h3> 

<p></br> <%= link_to 'Faite chauffer le clavier !', new_gossip_path %></br> </p>

<h3> Sinon, voici un peu de lecture. </h3>

<%@gossips.each_with_index do |gossip_to_view, index|%>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%=gossip_to_view.title %> </h5>
    <h6 class="card-subtitle mb-2 text-muted">De <%= gossip_to_view.user.first_name%></h6>
    <p class="card-text"><em>"<%=gossip_to_view.content%>"</em></p>
    <p> <%=gossip_to_view.comments.length%> commentaire(s) <a href="#" class="card-link"><%= link_to "Voir", gossip_path(gossip_to_view.id) %></a>    
  </div>
</div>
<p></p>

<%end%>


 

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<form action= "/gossips" method="POST">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   
   
    
    <div class="col">
        <label for="exampleInputEmail1">Titre</label>
        <input type="text" class="form-control" placeholder="Entrez le titre de votre potin" name="title">
    </div>
    

    

    <div class="form-group">
        <label for="exampleFormControlTextarea1">contenu</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="C'est partie le potin!" name="content"></textarea>
    </div>

   
   
          

    
    <input type="submit" value="Publier">
</form>

<%= link_to 'Retour', gossips_path %>

app/views/gossips/show.html.erb
<h2> <%=@gossip.title%> </h2>
<p> <em>"<%=@gossip.content%>" </em> </p>
<%autor = @gossip.user.first_name + " " + @gossip.user.last_name%>
<p> <strong>L'auteur :</strong> <%= link_to autor, user_path(@gossip.user.id) %></p>


<p><%= link_to 'Editer le potin', edit_gossip_path(@gossip) %> |
<%= link_to 'Detruire le potin', @gossip, method: :delete, data: { confirm: 'Etes vous sûr?' } %></br>


<p></br><strong>Les commentaires:</strong></p>
<%@gossip.comments.each do |comment|%>
<p> </br><em>"<%=comment.content%>" </em> </p>
<p>De <a href="<%=user_path(comment.user.id)%>"> <%=comment.user.first_name%> <%=comment.user.last_name%></a></p>

<%end%>

<form action= "/gossips/<%=@gossip.id%>/comments"<%=@gossip.id%>" method="POST">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
           
    

    <div class="form-group">        
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"  name="content"></textarea>
    </div>      
    
    <input type="submit" value="Laisser un commentaire">
</form>

</br>|<%= link_to 'Retour', gossips_path %>|</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>J29TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <!-- Fixed navbar -->
    
    
    <header>
              <nav class="navbar navbar-expand-md  navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="<%=gossips_path%>">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link " href="<%=root_path%>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=team_path%>">La Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="<%=contact_path%>">Contacte</a>
            </li>
             
          </ul>
          
        </div>
        <a class="nav-link " href=""><%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>
      </nav>

    </header>



    
    <p></br></br></p>
    <div>
      <% flash.each do |type, msg| %>
        <% if type == 'notice' %>
          <div class="alert alert-success mw-25 bg-success align-middle text-center" role="alert">
            <%= msg %>
          </div>
        <% else %>
          <div class="alert alert-primary mx-25 bg-danger align-middle text-center" role="alert">
            <%= msg %>
          </div>  
        <% end %>
      <% end %>
    </div>
    <p> </br> </br></p>    
    <main role="main" class="container">
    

    <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>The Gossip Project</h1>
<h2>Création d'un compte</h2>
<p></p>

<form action= "/users" method="POST">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   
   
    <div class="row">
        <div class="col">
            <label for="exampleInputEmail1">Prénom *</label>
            <input type="text" class="form-control" placeholder="Entrez votre prénom" name="first_name">
        </div>
        <div class="col">
            <label for="exampleInputEmail1">Nom de famille *</label>
            <input type="text" class="form-control" placeholder="Entrez votre nom de famille" name="last_name">
        </div>
    </div> 

    <div class="form-group">
        <label for="exampleInputEmail1">Adresse Email *</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrez votre email" name="email">
        <small id="emailHelp" class="form-text text-muted">Cet email vous servira d'identifiant</small>
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Présentez vous en quelques ligne" name="description"></textarea>
    </div>

   
    <div class="row">
        <div class="col">

            <div class="form-group">
                <label for="exampleFormControlSelect1">Choisissez une ville *</label>
                <select class="form-control" id="exampleFormControlSelect1" name="city">
                <option>AMIENS</option>
                <option>BORDEAUX</option>
                <option>LILLE</option>
                <option>MONPELLIER</option>
                <option>NANTES</option>
                <option>NICE</option>
                <option>PARIS</option>
                <option>RENNES</option>
                <option>STRASBOURG</option>
                <option>TOULOUSE</option>
                </select>
            </div>

            <label for="exampleInputEmail1">Votre âge </label>
            <input type="number" class="form-control" name="age" min="14" max="100">

            
            <label for="inputPassword" >Mot de passe *</label>                
            <input type="password" class="form-control" id="inputPassword" placeholder="Créer votre mot de passe" name="password">

            <label for="inputPassword" >Confirmation du mot de passe *</label>                
            <input type="password" class="form-control" id="inputPassword" placeholder="Confirmer votre mot de passe"name ="password_confirmation">
                
            

        </div>


        <div class="col">
        </div>

    </div>
    <p></br>* Champs obligatoires</p>

    
    <input type="submit" value="S'inscrire">
</form>

app/views/users/show.html.erb
<h1> <%=@user.first_name%> <%=@user.last_name%> </h1>

<p><strong>Ville :</strong> <a href="<%=city_path(@user.city.id)%>"> <%=@user.city.name%> </a> </p>

<p><strong>Age :</strong> <%=@user.age%> ans</p>

<p><strong>Description:</strong> <%=@user.description%> </p>

<p><strong>Email :</strong> <%=@user.email%> </p>

<p><strong>Ses gossips :</strong> </p>


<%@user.gossips.each do |gossip|%>
<p><%=gossip.title%></br><em>"<%=gossip.content%>"</em></br></p>
<%end%>

<%= link_to 'Retour à goosip\'s lande', gossips_path %>